In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [ ]:
df.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3)

In [ ]:
bow=cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people': 2, 'campusx': 0, 'comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1]]
[[2 0 0]]


In [ ]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0]])

N grams

In [ ]:
cv=CountVectorizer(ngram_range=(2,2))

In [ ]:
bow=cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [ ]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[1, 0, 0, 0, 0, 1]])

TF-IDF Vectorization

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [ ]:
bow=tf.fit_transform(df['text'])

In [ ]:
bow[0].toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ]])

In [ ]:
tf.idf_

array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562])

Excercise

In [ ]:
import pandas as pd

data=pd.read_csv("/content/data/IMDB Dataset.csv")

In [ ]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

Text Classification

In [27]:
import numpy as np
import pandas as pd

In [28]:
dataset=pd.read_csv("./data/IMDB Dataset.csv")

In [29]:
dataset.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
dataset['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [ ]:
dataset.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
dataset.duplicated().sum()

17

In [30]:
dataset.drop_duplicates(inplace=True)

In [ ]:
dataset.duplicated().sum()

0

In [ ]:
dataset['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

Minimizing the data

In [31]:
dataset=dataset.iloc[:10000]

In [32]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

def lower_case(text):
  return text.lower()


def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

def remove_stop_words(text):
  words_list=word_tokenize(text)
  removed_words_list = [word for word in words_list if word not in stopwords.words('english')]
  return ' '.join(removed_words_list)




[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [33]:
dataset['review']=dataset['review'].apply(remove_html_tags)

In [34]:
dataset['review']=dataset['review'].apply(lower_case)

In [35]:
dataset['review']=dataset['review'].apply(remove_stop_words)

In [ ]:
dataset['review'][1]

"wonderful little production . filming technique unassuming- old-time-bbc fashion gives comforting , sometimes discomforting , sense realism entire piece . actors extremely well chosen- michael sheen `` got polari '' voices pat ! truly see seamless editing guided references williams ' diary entries , well worth watching terrificly written performed piece . masterful production one great master 's comedy life . realism really comes home little things : fantasy guard , rather use traditional 'dream ' techniques remains solid disappears . plays knowledge senses , particularly scenes concerning orton halliwell sets ( particularly flat halliwell 's murals decorating every surface ) terribly well done ."

In [ ]:
dataset.head()

review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production . filming techniqu...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically 's family little boy ( jake ) thinks...  negative
4  petter mattei 's `` love time money '' visuall...  positive

In [ ]:
x=dataset.iloc[:,0:1]
y=dataset['sentiment']

In [ ]:
x
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
10012    positive
10013    positive
10014    negative
10015    positive
10016    negative
Name: sentiment, Length: 10000, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [ ]:
y=encoder.fit_transform(y)

In [ ]:
y

array([1, 1, 1, ..., 0, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split

x_train , x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train.shape

(8000, 1)

In [ ]:
x_test.shape

(2000, 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

In [ ]:
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()

In [ ]:
x_test_bow.shape

(2000, 48337)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

gnb.fit(x_train_bow,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(x_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6375

In [ ]:
confusion_matrix(y_test,y_pred)

array([[733, 260],
       [465, 542]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

rf.fit(x_train_bow,y_train)
y_prediction=rf.predict(x_test_bow)
accuracy_score(y_test,y_prediction)

0.85

In [ ]:
cv=CountVectorizer(max_features=3000)
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()

In [ ]:
rf=RandomForestClassifier()

rf.fit(x_train_bow,y_train)
y_prediction=rf.predict(x_test_bow)
accuracy_score(y_test,y_prediction)

0.843

In [ ]:
# We can use ngram as well

cv=CountVectorizer(ngram_range=(1,2))
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()
rf=RandomForestClassifier()

rf.fit(x_train_bow,y_train)
y_prediction=rf.predict(x_test_bow)
accuracy_score(y_test,y_prediction)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer()

In [ ]:
x_tfidf_bow=tfidf.fit_transform(x_train['review']).toarray()
x_test_tfidf_bow=tfidf.transform(x_test['review']).toarray()

In [ ]:
rf=RandomForestClassifier()

rf.fit(x_tfidf_bow,y_train)
y_prediction=rf.predict(x_test_tfidf_bow)
accuracy_score(y_test,y_prediction)

0.8515

Word2Vec

In [ ]:
!pip install gensim

In [37]:
import gensim

In [36]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [42]:
story=[]
for doc in dataset['review']:
  raw_sent = sent_tokenize(doc)
  for sent in raw_sent:
      story.append(simple_preprocess(sent))


In [ ]:
story

In [58]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [59]:
model.build_vocab(story)

In [60]:
print(model.epochs)

model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

5


(5675972, 6007315)

In [62]:
len(model.wv.index_to_key)

31881

In [63]:
def document_vector(doc):
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  return np.mean(model.wv[doc],axis=0)

In [66]:
document_vector(dataset['review'].values[0])

array([-0.1046506 ,  0.25021824, -0.14915305,  0.03784987,  0.14774972,
       -0.5165438 , -0.00186628,  0.81218964, -0.3380294 , -0.2037818 ,
       -0.16265278, -0.39420557,  0.04791718,  0.13995749,  0.16594383,
       -0.30481318,  0.0927388 , -0.32805327,  0.068174  , -0.67111593,
        0.41323304,  0.16623543,  0.27770203, -0.3407362 ,  0.10986684,
       -0.12798536, -0.27054486, -0.29365227, -0.41357613,  0.14374247,
        0.4000722 ,  0.17664716, -0.02409678, -0.4256988 , -0.01226704,
        0.3835481 ,  0.00576425, -0.14312032, -0.08912909, -0.6785928 ,
        0.15639897, -0.36725083, -0.03166858, -0.02993292,  0.28203312,
       -0.08952188, -0.2196833 ,  0.04446291,  0.29296643,  0.2325837 ,
        0.22364779, -0.31816906, -0.22478269, -0.03153261, -0.13788132,
        0.28584135,  0.20515093, -0.03817094, -0.28453335,  0.12594736,
        0.0522013 ,  0.370186  , -0.08125228,  0.01289706, -0.38407937,
        0.32928416,  0.11281364,  0.15394844, -0.51583874,  0.40

In [67]:
from tqdm import tqdm

In [68]:
x=[]
for doc in tqdm(dataset['review'].values):
  x.append(document_vector(doc))

100%|██████████| 10000/10000 [09:08<00:00, 18.22it/s]


In [69]:
x=np.array(x)

In [70]:
x.shape

(10000, 100)

In [71]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [72]:
from sklearn.model_selection import train_test_split

x_train , x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [73]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

rf.fit(x_train,y_train)
y_prediction=rf.predict(x_test)
accuracy_score(y_test,y_prediction)

0.772